---
- name: Validate server authentication input provided by user
  when:
  - (username is not defined or password is not defined) and (auth_token is not defined)
  ansible.builtin.fail:
    msg: "username/password or auth_token is mandatory"

    - name: Fail when more than one valid authentication method is provided
      when:
      - ((username is defined or password is defined) and auth_token is defined)
      ansible.builtin.fail:
        msg: "Only one authentication method is allowed. Provide either username/password or auth_token."

    msg: "{{ result }}"

