---
- name: Validate server authentication input provided by user
  fail:
    msg: "auth_token is mandatory"
  when:
  - (auth_token is not defined)

  register: user_privileges

- ilo_manage:
    category: "Systems"
    command: "CheckUserPrivileges"
    baseuri: "{{ baseuri }}"
    auth_token: "{{ auth_token }}"
    required_permissions: "{{ required_permissions | default(['HostBIOSConfigPriv', 'HostNICConfigPriv', 'HostStorageConfigPriv']) }}"
  register: result

