---
- hosts: myhosts
  connection: local
  gather_facts: false
  tasks:
    - name: Validate server authentication input provided by user
      when:
        - (username is not defined or password is not defined) and (auth_token is not defined)
      ansible.builtin.fail:
        msg: username/password or auth_token is mandatory

    - name: Fail when more than one valid authentication method is provided
      when:
        - ((username is defined or password is defined) and auth_token is defined)
      ansible.builtin.fail:
        msg: Only one authentication method is allowed. Provide either username/password or auth_token.

    - name: Get BIOS registries when username and password are defined
      block:
        - community.general.redfish_info:
            category: Systems
            command: GetBiosRegistries
            baseuri: "{{ baseuri }}"
            username: "{{ username }}"
            password: "{{ password }}"
          register: bios_registries

        - name: BIOS registries details
          debug:
            msg: "{{ bios_registries }}"

      when: username is defined and password is defined

    - name: Get BIOS registries when auth_token is defined
      block:
        - community.general.redfish_info:
            category: Systems
            command: GetBiosRegistries
            baseuri: "{{ baseuri }}"
            auth_token: "{{ auth_token }}"
          register: bios_registries

        - name: BIOS registries details
          debug:
            msg: "{{ bios_registries }}"

      when: auth_token is defined
