---
- hosts: myhosts
  connection: local
  gather_facts: False
  tasks:
    - name: Validate server authentication input provided by user
      when:
      - (username is not defined or password is not defined) and (auth_token is not defined)
      ansible.builtin.fail:
        msg: "username/password or auth_token is mandatory"

    - name: Fail when more than one valid authentication method is provided
      when:
      - ((username is defined or password is defined) and auth_token is defined)
      ansible.builtin.fail:
        msg: "Only one authentication method is allowed. Provide either username/password or auth_token."

          ((username is defined or password is defined) and auth_token is defined) or
          ((cert_file is defined or key_file is defined) and auth_token is defined)
- community.general.redfish_command:
    category: "Systems"
    command: "VerifyBiosAttributes"
    baseuri: "{{ _baseuri_ }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    bios_attributes: "{{ _bios_attributes_ }}"
  register: result

            bios_attributes: "{{ bios_attributes }}"
          register: result

        - name: Status
          debug:
            msg: "{{ result }}"

      when: username is defined and password is defined

    - name: Verify BIOS attributes when cert_file and key_file are defined
      block:
        - community.general.redfish_command:
            category: Systems
            command: VerifyBiosAttributes
            baseuri: "{{ baseuri }}"
            cert_file: "{{ cert_file }}"
        - name: Status
          debug:
            msg: "{{ result }}"

      when: auth_token is defined
            msg: "{{ result }}"

      when: cert_file is defined and key_file is defined

    - name: Verify BIOS attributes when auth_token is defined
      block:
        - community.general.redfish_command:
            category: Systems
            command: VerifyBiosAttributes
            baseuri: "{{ baseuri }}"
            auth_token: "{{ auth_token }}"
            bios_attributes: "{{ bios_attributes }}"
          register: result

        - name: Status
          debug:
            msg: "{{ result }}"

      when: auth_token is defined
