---
- hosts: myhosts
  connection: local
  gather_facts: False
  tasks:
    - name: Validate server authentication input provided by user
      when:
      - (username is not defined or password is not defined) and (auth_token is not defined)
      ansible.builtin.fail:
        msg: "username/password or auth_token is mandatory"

    - name: Fail when more than one valid authentication method is provided
      when:
      - ((username is defined or password is defined) and auth_token is defined)
      ansible.builtin.fail:
        msg: "Only one authentication method is allowed. Provide either username/password or auth_token."

    - name: Verify BIOS attributes when username and password are defined
      block:
        - community.general.redfish_command:
            category: Systems
            command: VerifyBiosAttributes
            baseuri: "{{ baseuri }}"
            username: "{{ username }}"
            password: "{{ password }}"
            bios_attributes: "{{ bios_attributes }}"
          register: result

        - name: Status
          debug:
            msg: "{{ result }}"

      when: username is defined and password is defined

    - name: Verify BIOS attributes when auth_token is defined
      block:
        - community.general.redfish_command:
            category: Systems
            command: VerifyBiosAttributes
            baseuri: "{{ baseuri }}"
            auth_token: "{{ auth_token }}"
            bios_attributes: "{{ bios_attributes }}"
          register: result

        - name: Status
          debug:
            msg: "{{ result }}"

      when: auth_token is defined
