---
# tasks file for ledon
- name: Turn LED on
  hpe.ilo.ilo_device:
    category: Chassis
    command: IndicatorLedOn
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
