---
# tasks file for ledoff
- name: Turn LED off
  hpe.ilo.ilo_device:
    category: Chassis
    command: IndicatorLedOff
    baseuri: "{{ baseuri }}"
    username: "{{ username }}"
    password: "{{ password }}"
