---
- hosts: myhosts
  connection: local
  gather_facts: False
  tasks:
    - name: Validate server authentication input provided by user
      fail:
        msg: "auth_token is mandatory"
      when:
      - (auth_token is not defined)

    - name: Fail when more than one valid authentication method is provided
      fail:
        - ilo_manage:
            category: "Systems"
            command: "CheckUserPrivileges"
            baseuri: "{{ baseuri }}"
            auth_token: "{{ auth_token }}"
            required_permissions: "{{ required_permissions | default(['HostBIOSConfigPriv', 'HostNICConfigPriv', 'HostStorageConfigPriv']) }}"
          register: result

        - name: User Privileges Status
          debug:
            msg: "{{ result }}"

      when: auth_token is defined
          register: result

        - name: User Privileges
          debug:
            msg: "{{ result }}"

      when: auth_token is defined
