---
- name: Validate server authentication input provided by user
  fail:
    msg: "username/password or cert_file/key_file or auth_token is mandatory"
  when:
  - (username is not defined or password is not defined) and (cert_file is not defined or key_file is not defined) and (auth_token is not defined)

    - name: Fail when more than one valid authentication method is provided
      fail:
        msg: "Only one authentication method is allowed. Provide either username/password or cert_file/key_file or auth_token."
      when:
      - ((username is defined or password is defined) and (cert_file is defined or key_file is defined) and auth_token is defined) or ((username is defined or password is defined) and (cert_file is defined or key_file is defined)) or ((username is defined or password is defined) and auth_token is defined) or ((cert_file is defined or key_file is defined) and auth_token is defined)

    - name: Check whether maintenance window is provided
      set_fact:
        maintenance_window_flag: "{{ True if maintenance_window_details is defined else False}}"

    - name: Perform firmware upgrade on the server without maintenance window through install set URL
      ilo_firmware:
        category: UpdateService
        command: UpdateFirmwareThroughInstallSet
        - name: Perform firmware upgrade on the server without maintenance window using install set when username and password are defined
          ilo_firmware:
            category: "UpdateService"
            command: "UpdateFirmwareThroughInstallSet"
            baseuri: "{{ baseuri }}"
            username: "{{ username }}"
            password: "{{ password }}"
            install_set_attributes: "{{ install_set_attributes }}"
          register: firmware_upgrade_rsp

      - name: Collecting server IP, task ID(s) and URL details when username and password are defined
        set_fact:
          server_rsp_details:
            Server: '{{ baseuri }}'
            Tasks: "{{ firmware_upgrade_rsp['ilo_firmware']['UpdateFirmwareThroughInstallSet']['msg'] }}"

        - name: Firmware upgrade status when username and password are defined
          debug:
            msg: "{{ server_rsp_details }}"
      when: not maintenance_window_flag

        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        - name: Perform firmware upgrade on the server with maintenance window using install set when username and password are defined
          ilo_firmware:
            category: "UpdateService"
            command: "UpdateFirmwareThroughInstallSet"
            baseuri: "{{ baseuri }}"
            username: "{{ username }}"
            password: "{{ password }}"
            install_set_attributes: "{{ install_set_attributes }}"
            maintenance_window_details: "{{ maintenance_window_details }}"
          register: firmware_upgrade_rsp

- name: Collecting server IP, task ID(s) and URL details when username and password are defined
  set_fact:
    server_rsp_details:
      Server: '{{ baseuri }}'
      Tasks: "{{ firmware_upgrade_rsp['ilo_firmware']['UpdateFirmwareThroughInstallSet']['msg'] }}"

